server:
  port: 5000
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:tecnoestagio
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  h2:
    console:
      enabled: true
      
